import type { Lead, Call, AgentConfig, Appointment, DailyMetric, AgentMetrics } from '@/types';

// ============================================
// Mock-Daten für Dashboard & Entwicklung
// ============================================

export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    vorname: 'Thomas',
    nachname: 'Müller',
    telefon: '+49 89 1234567',
    email: 't.mueller@email.de',
    adresse: 'Marienplatz 5',
    plz: '80331',
    ort: 'München',
    status: 'termin_gebucht',
    quelle: 'kaltakquise',
    heizungsart: 'gasheizung',
    gebaeudeart: 'einfamilienhaus',
    wohnflaeche: 140,
    baujahr: 1985,
    notizen: 'Interessiert an Wärmepumpe. Alte Gasheizung von 1998.',
    letzterKontakt: '2024-06-05T14:30:00',
    naechsterTermin: '2024-06-12T10:00:00',
    erstelltAm: '2024-06-01T09:00:00',
    aktualisiertAm: '2024-06-05T14:30:00',
  },
  {
    id: 'lead-002',
    vorname: 'Sabine',
    nachname: 'Schmidt',
    telefon: '+49 30 9876543',
    email: 's.schmidt@web.de',
    adresse: 'Kurfürstendamm 120',
    plz: '10711',
    ort: 'Berlin',
    status: 'interessiert',
    quelle: 'website',
    heizungsart: 'oelheizung',
    gebaeudeart: 'altbau',
    wohnflaeche: 95,
    baujahr: 1960,
    notizen: 'Ölheizung defekt, braucht schnelle Lösung. Interesse an Hybridheizung.',
    letzterKontakt: '2024-06-04T11:15:00',
    erstelltAm: '2024-05-28T10:00:00',
    aktualisiertAm: '2024-06-04T11:15:00',
  },
  {
    id: 'lead-003',
    vorname: 'Michael',
    nachname: 'Weber',
    telefon: '+49 211 5551234',
    adresse: 'Rheinallee 45',
    plz: '40545',
    ort: 'Düsseldorf',
    status: 'angebot_gesendet',
    quelle: 'empfehlung',
    heizungsart: 'gasheizung',
    gebaeudeart: 'einfamilienhaus',
    wohnflaeche: 180,
    baujahr: 1975,
    notizen: 'Angebot für Wärmepumpe + Fußbodenheizung gesendet. Hohe Kaufabsicht.',
    letzterKontakt: '2024-06-03T16:00:00',
    erstelltAm: '2024-05-20T08:30:00',
    aktualisiertAm: '2024-06-03T16:00:00',
  },
  {
    id: 'lead-004',
    vorname: 'Klaus',
    nachname: 'Fischer',
    telefon: '+49 69 7778899',
    adresse: 'Zeil 78',
    plz: '60313',
    ort: 'Frankfurt',
    status: 'neu',
    quelle: 'werbung',
    heizungsart: 'unbekannt',
    gebaeudeart: 'mehrfamilienhaus',
    wohnflaeche: 320,
    baujahr: 1990,
    erstelltAm: '2024-06-06T07:45:00',
    aktualisiertAm: '2024-06-06T07:45:00',
  },
  {
    id: 'lead-005',
    vorname: 'Anna',
    nachname: 'Becker',
    telefon: '+49 711 3334455',
    email: 'anna.becker@gmx.de',
    adresse: 'Königstraße 22',
    plz: '70173',
    ort: 'Stuttgart',
    status: 'gewonnen',
    quelle: 'kaltakquise',
    heizungsart: 'waermepumpe',
    gebaeudeart: 'neubau',
    wohnflaeche: 160,
    baujahr: 2024,
    notizen: 'Vertrag unterschrieben! Wärmepumpe + Solarthermie. Installationsbeginn Juli.',
    letzterKontakt: '2024-06-02T09:00:00',
    erstelltAm: '2024-05-10T11:00:00',
    aktualisiertAm: '2024-06-02T09:00:00',
  },
  {
    id: 'lead-006',
    vorname: 'Petra',
    nachname: 'Hoffmann',
    telefon: '+49 40 2223344',
    adresse: 'Jungfernstieg 15',
    plz: '20354',
    ort: 'Hamburg',
    status: 'kontaktiert',
    quelle: 'kaltakquise',
    heizungsart: 'gasheizung',
    gebaeudeart: 'altbau',
    wohnflaeche: 85,
    baujahr: 1955,
    notizen: 'Rückruf erwünscht am Freitag Nachmittag.',
    letzterKontakt: '2024-06-05T13:00:00',
    erstelltAm: '2024-06-03T14:00:00',
    aktualisiertAm: '2024-06-05T13:00:00',
  },
  {
    id: 'lead-007',
    vorname: 'Markus',
    nachname: 'Wagner',
    telefon: '+49 89 1112233',
    adresse: 'Leopoldstraße 90',
    plz: '80802',
    ort: 'München',
    status: 'interessiert',
    quelle: 'empfehlung',
    heizungsart: 'gasheizung',
    gebaeudeart: 'einfamilienhaus',
    wohnflaeche: 200,
    baujahr: 1970,
    notizen: 'Möchte Klimaanlage für Obergeschoss + Heizungssanierung. Doppelinteresse.',
    letzterKontakt: '2024-06-06T08:30:00',
    erstelltAm: '2024-05-25T10:00:00',
    aktualisiertAm: '2024-06-06T08:30:00',
  },
  {
    id: 'lead-008',
    vorname: 'Julia',
    nachname: 'Koch',
    telefon: '+49 221 4445566',
    email: 'j.koch@outlook.de',
    adresse: 'Hohe Straße 33',
    plz: '50667',
    ort: 'Köln',
    status: 'termin_gebucht',
    quelle: 'website',
    heizungsart: 'gasheizung',
    gebaeudeart: 'einfamilienhaus',
    wohnflaeche: 120,
    baujahr: 1995,
    notizen: 'Termin für Solarthermie-Beratung. Dach nach Süden ausgerichtet.',
    letzterKontakt: '2024-06-04T15:00:00',
    naechsterTermin: '2024-06-11T14:00:00',
    erstelltAm: '2024-06-01T12:00:00',
    aktualisiertAm: '2024-06-04T15:00:00',
  },
];

export const mockCalls: Call[] = [
  {
    id: 'call-001',
    leadId: 'lead-001',
    leadName: 'Thomas Müller',
    status: 'abgeschlossen',
    ergebnis: 'termin_gebucht',
    dauer: 485,
    gestartetAm: '2024-06-05T14:30:00',
    beendetAm: '2024-06-05T14:38:05',
    skriptId: 'script-waermepumpe-01',
    stimmung: 'positiv',
    transkript: [
      { id: 't-1', callId: 'call-001', abschnitt: 'begruessung', sprecher: 'agent', text: 'Guten Tag Herr Müller, mein Name ist Anna von HeizPro. Ich rufe Sie heute an...', zeitstempel: '2024-06-05T14:30:00' },
      { id: 't-2', callId: 'call-001', abschnitt: 'begruessung', sprecher: 'kunde', text: 'Guten Tag, ja ich höre zu.', zeitstempel: '2024-06-05T14:30:15' },
      { id: 't-3', callId: 'call-001', abschnitt: 'bedarfsanalyse', sprecher: 'agent', text: 'Super! Darf ich fragen, wie alt Ihre aktuelle Heizung ist?', zeitstempel: '2024-06-05T14:30:25' },
      { id: 't-4', callId: 'call-001', abschnitt: 'bedarfsanalyse', sprecher: 'kunde', text: 'Die ist von 1998, eine Gasheizung. Läuft noch, aber ich weiß, dass sie bald ausgetauscht werden muss.', zeitstempel: '2024-06-05T14:30:35' },
      { id: 't-5', callId: 'call-001', abschnitt: 'praesentation', sprecher: 'agent', text: 'Genau! Da haben wir die perfekte Lösung. Eine Wärmepumpe spart Ihnen bis zu 60%...', zeitstempel: '2024-06-05T14:31:00' },
      { id: 't-6', callId: 'call-001', abschnitt: 'abschluss', sprecher: 'kunde', text: 'Das klingt interessant. Lassen Sie uns einen Termin machen.', zeitstempel: '2024-06-05T14:35:30' },
    ],
    zusammenfassung: 'Kunde hat alte Gasheizung (1998). Starkes Interesse an Wärmepumpe. Termin für Vor-Ort-Beratung am 12.06. vereinbart.',
    terminGebucht: true,
    terminDatum: '2024-06-12T10:00:00',
  },
  {
    id: 'call-002',
    leadId: 'lead-002',
    leadName: 'Sabine Schmidt',
    status: 'abgeschlossen',
    ergebnis: 'interesse',
    dauer: 620,
    gestartetAm: '2024-06-04T11:15:00',
    beendetAm: '2024-06-04T11:25:20',
    skriptId: 'script-waermepumpe-01',
    stimmung: 'neutral',
    transkript: [],
    zusammenfassung: 'Ölheizung defekt. Kunde braucht schnelle Lösung. Interesse an Hybrid, aber Bedenken wegen Kosten. Rückruf mit Angebot nächste Woche.',
  },
  {
    id: 'call-003',
    leadId: 'lead-003',
    leadName: 'Michael Weber',
    status: 'abgeschlossen',
    ergebnis: 'termin_gebucht',
    dauer: 390,
    gestartetAm: '2024-06-03T16:00:00',
    beendetAm: '2024-06-03T16:06:30',
    skriptId: 'script-waermepumpe-01',
    stimmung: 'positiv',
    transkript: [],
    zusammenfassung: 'Empfehlungskunde. Hohes Budget. Interesse an Wärmepumpe + Fußbodenheizung. Angebot bereits gesendet.',
    terminGebucht: true,
  },
  {
    id: 'call-004',
    leadId: 'lead-006',
    leadName: 'Petra Hoffmann',
    status: 'abgeschlossen',
    ergebnis: 'rueckruf',
    dauer: 180,
    gestartetAm: '2024-06-05T13:00:00',
    beendetAm: '2024-06-05T13:03:00',
    skriptId: 'script-gasheizung-01',
    stimmung: 'neutral',
    transkript: [],
    zusammenfassung: 'Kunde hat aktuell keine Zeit. Rückruf am Freitag Nachmittag vereinbart.',
  },
  {
    id: 'call-005',
    leadId: 'lead-007',
    leadName: 'Markus Wagner',
    status: 'abgeschlossen',
    ergebnis: 'interesse',
    dauer: 720,
    gestartetAm: '2024-06-06T08:30:00',
    beendetAm: '2024-06-06T08:42:00',
    skriptId: 'script-klimaanlage-01',
    stimmung: 'positiv',
    transkript: [],
    zusammenfassung: 'Doppelinteresse: Klimaanlage für OG + Heizungssanierung. Budget vorhanden. Termin in Planung.',
  },
  {
    id: 'call-006',
    leadId: 'lead-004',
    leadName: 'Klaus Fischer',
    status: 'geplant',
    dauer: 0,
    gestartetAm: '2024-06-06T15:00:00',
    skriptId: 'script-waermepumpe-01',
    transkript: [],
  },
];

export const mockAgent: AgentConfig = {
  id: 'agent-01',
  name: 'Anna – Bauberaterin',
  beschreibung: 'Ruhige, vertrauensvolle Beraterin. Spezialisiert auf Heizungssanierung und Energiewende. Perfekt fuer anspruchsvolle Hausbesitzer.',
  persoenlichkeit: 'beratend',
  sprache: 'de-DE',
  stimme: 'Marlene',
  geschwindigkeit: 1.0,
  temperatur: 0.7,
  aktiv: true,
  maxAnrufeProTag: 80,
  arbeitszeiten: {
    start: '09:00',
    ende: '18:00',
    wochentage: [1, 2, 3, 4, 5],
  },
  skriptIds: ['script-waermepumpe-01', 'script-klimaanlage-01', 'script-gasheizung-01'],
  niches: ['waermepumpe', 'klimaanlage', 'gasheizung', 'solarthermie'],
  erstelltAm: '2024-01-01',
};

export const mockAgents: AgentConfig[] = [
  mockAgent,
  {
    id: 'agent-02',
    name: 'Max – Verkaufsprofi',
    beschreibung: 'Energisch und zielorientiert. Abschlussstark mit Fokus auf schnelle Terminbuchung. Ideal fuer Kurzgespraeche und iPhones.',
    persoenlichkeit: 'energisch',
    sprache: 'de-DE',
    stimme: 'Daniel',
    geschwindigkeit: 1.1,
    temperatur: 0.8,
    aktiv: true,
    maxAnrufeProTag: 100,
    arbeitszeiten: {
      start: '08:00',
      ende: '20:00',
      wochentage: [1, 2, 3, 4, 5, 6],
    },
    skriptIds: ['script-waermepumpe-01', 'script-gasheizung-01'],
    niches: ['waermepumpe', 'gasheizung', 'hybridheizung', 'pelletsheizung'],
    erstelltAm: '2024-01-01',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-001',
    leadId: 'lead-001',
    leadName: 'Thomas Müller',
    datum: '2024-06-12',
    uhrzeit: '10:00',
    dauer: 60,
    ort: 'Marienplatz 5, 80331 München',
    niche: 'waermepumpe',
    status: 'bestaetigt',
    notizen: 'Vor-Ort-Beratung Wärmepumpe. Alte Gasheizung prüfen.',
  },
  {
    id: 'apt-002',
    leadId: 'lead-008',
    leadName: 'Julia Koch',
    datum: '2024-06-11',
    uhrzeit: '14:00',
    dauer: 45,
    ort: 'Hohe Straße 33, 50667 Köln',
    niche: 'solarthermie',
    status: 'geplant',
    notizen: 'Solarthermie-Beratung, Dach nach Süden.',
  },
  {
    id: 'apt-003',
    leadId: 'lead-003',
    leadName: 'Michael Weber',
    datum: '2024-06-14',
    uhrzeit: '11:00',
    dauer: 90,
    ort: 'Rheinallee 45, 40545 Düsseldorf',
    niche: 'waermepumpe',
    status: 'geplant',
    notizen: 'Wärmepumpe + Fußbodenheizung Angebot besprechen.',
  },
];

export const mockDailyMetrics: DailyMetric[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  const base = 40 + Math.random() * 30;
  const verbunden = Math.floor(base * (0.55 + Math.random() * 0.2));
  const termine = Math.floor(verbunden * (0.1 + Math.random() * 0.08));
  const abschluesse = Math.floor(termine * (0.2 + Math.random() * 0.15));
  return {
    datum: date.toISOString().split('T')[0],
    anrufe: Math.floor(base),
    verbunden,
    termine,
    abschluesse,
    dauerDurchschnitt: Math.floor(180 + Math.random() * 300),
  };
});

export const mockAgentMetrics: AgentMetrics = {
  totalAnrufe: 1247,
  verbundenRate: 0.62,
  terminQuote: 0.14,
  abschlussRate: 0.08,
  durchschnittlicheDauer: 312,
  umsatzMonat: 127500,
  topNiche: 'waermepumpe',
  trends: {
    anrufe: 12,
    termine: 18,
    abschluesse: 5,
  },
};
